*** Variables ***
${SHOPPING_CART_GO_TO_CHECKOUT_BUTTON}                    css=a.btn.btn-primary[href*="objednavka"]
${SHOPPING_CART_FORM_CONTINUE_BUTTON}                     css=button.continue[data-link-action="register-new-customer"]
${SHOPPING_CART_EMAIL_INPUT}                              css=input#field-email:not([autocomplete])
${SHOPPING_CART_PASSWORD_INPUT}                           css=input#field-password:not([autocomplete])
